// Interrupt Descriptor Table (IDT) + Exception/Interrupt Handlers
//
// The IDT is a table with 256 entries. Each entry says:
//   "When interrupt N fires, jump to THIS function."
//
// Interrupts come from three sources:
//   1. CPU exceptions (divide-by-zero, page fault, double fault, etc.)
//      — generated by the CPU itself when something goes wrong
//   2. Hardware interrupts (timer, keyboard, disk, etc.)
//      — generated by external devices via the PIC chip
//   3. Software interrupts (int3, syscall, etc.)
//      — generated intentionally by code using INT instruction
//
// We set up handlers for:
//   Entry  3: Breakpoint (INT3) — debugger trap
//   Entry  8: Double fault — an exception handler itself faulted
//   Entry 14: Page fault — accessed unmapped/protected memory
//   Entry 32: Timer (IRQ 0) — fires ~18 times/sec from PIT chip
//   Entry 33: Keyboard (IRQ 1) — a key was pressed or released

use crate::gdt;
use crate::{print, println};
use lazy_static::lazy_static;
use pic8259::ChainedPics;
use spin;
use x86_64::structures::idt::{InterruptDescriptorTable, InterruptStackFrame, PageFaultErrorCode};

// ── PIC Configuration ────────────────────────────────────────────────
//
// The PIC (Programmable Interrupt Controller) is a chip that sits between
// hardware devices and the CPU. There are actually TWO PICs chained together:
//   PIC1: handles IRQ 0-7
//   PIC2: handles IRQ 8-15
//
// By default, PIC1 maps IRQ 0-7 to interrupt numbers 0-7. But interrupt
// numbers 0-31 are reserved for CPU exceptions! So IRQ 0 (timer) would
// collide with interrupt 0 (divide error). We REMAP the PICs:
//   PIC1: IRQ 0-7  → interrupt 32-39
//   PIC2: IRQ 8-15 → interrupt 40-47

pub const PIC_1_OFFSET: u8 = 32;
pub const PIC_2_OFFSET: u8 = PIC_1_OFFSET + 8;

// The ChainedPics struct manages both PIC1 and PIC2 together.
// Wrapped in a spinlock because interrupt handlers can fire at any time.
pub static PICS: spin::Mutex<ChainedPics> =
    spin::Mutex::new(unsafe { ChainedPics::new(PIC_1_OFFSET, PIC_2_OFFSET) });

// ── Interrupt Index Enum ─────────────────────────────────────────────
//
// Maps hardware IRQ numbers to their remapped interrupt numbers.

#[derive(Debug, Clone, Copy)]
#[repr(u8)]
pub enum InterruptIndex {
    Timer = PIC_1_OFFSET,       // IRQ 0 → interrupt 32
    Keyboard,                    // IRQ 1 → interrupt 33 (next value automatically)
}

impl InterruptIndex {
    fn as_u8(self) -> u8 {
        self as u8
    }

    fn as_usize(self) -> usize {
        usize::from(self.as_u8())
    }
}

// ── IDT Setup ────────────────────────────────────────────────────────

lazy_static! {
    static ref IDT: InterruptDescriptorTable = {
        let mut idt = InterruptDescriptorTable::new();

        // CPU Exception handlers
        idt.breakpoint.set_handler_fn(breakpoint_handler);
        unsafe {
            // Double fault gets its own stack via the IST (Interrupt Stack Table).
            // This is critical: if the kernel stack overflows and causes a page
            // fault, the page fault handler runs on the same broken stack and
            // triggers a double fault. If the double fault handler ALSO uses
            // the broken stack, it triple faults (= instant reboot, no error).
            // By giving double fault its own clean stack, we can at least print
            // an error message before halting.
            idt.double_fault
                .set_handler_fn(double_fault_handler)
                .set_stack_index(gdt::DOUBLE_FAULT_IST_INDEX);
        }
        idt.page_fault.set_handler_fn(page_fault_handler);

        // Hardware interrupt handlers (remapped via PIC)
        idt[InterruptIndex::Timer.as_usize()].set_handler_fn(timer_interrupt_handler);
        idt[InterruptIndex::Keyboard.as_usize()].set_handler_fn(keyboard_interrupt_handler);

        // Software interrupt 0x80 — syscall entry point.
        // When user code executes `int 0x80`, the CPU jumps here.
        // This is the same mechanism Linux used before syscall/sysret.
        idt[0x80].set_handler_fn(crate::syscall::syscall_handler);

        idt
    };
}

// Load the IDT into the CPU.
pub fn init_idt() {
    IDT.load();
}

// ── Exception Handlers ───────────────────────────────────────────────

// Breakpoint (INT3) — the simplest exception to test.
// Debuggers insert INT3 (0xCC) at breakpoint locations.
// Unlike most exceptions, breakpoint is NOT fatal — execution continues.
//
// The `extern "x86-interrupt"` calling convention is special:
//   - The CPU pushes an InterruptStackFrame before calling the handler
//   - The handler returns via `iretq` instruction (not normal `ret`)
//   - The compiler handles saving/restoring all registers
extern "x86-interrupt" fn breakpoint_handler(stack_frame: InterruptStackFrame) {
    println!("EXCEPTION: BREAKPOINT\n{:#?}", stack_frame);
}

// Double fault — triggered when an exception handler itself causes an exception.
// This is our "last chance" handler before triple fault (reboot).
// It's DIVERGING (-> !) because recovery is not possible.
//
// The `_error_code` is always 0 for double faults, but the CPU pushes it
// anyway, so the function signature must accept it.
extern "x86-interrupt" fn double_fault_handler(
    stack_frame: InterruptStackFrame,
    _error_code: u64,
) -> ! {
    panic!("EXCEPTION: DOUBLE FAULT\n{:#?}", stack_frame);
}

// Page fault — triggered when code accesses:
//   - An unmapped virtual address (page not present)
//   - A page with insufficient permissions (e.g., writing to read-only)
//   - A user-mode access to a kernel page
//
// CR2 register automatically contains the virtual address that caused the fault.
extern "x86-interrupt" fn page_fault_handler(
    stack_frame: InterruptStackFrame,
    error_code: PageFaultErrorCode,
) {
    use x86_64::registers::control::Cr2;

    println!("EXCEPTION: PAGE FAULT");
    println!("Accessed Address: {:?}", Cr2::read());
    println!("Error Code: {:?}", error_code);
    println!("{:#?}", stack_frame);

    crate::hlt_loop();
}

// ── Hardware Interrupt Handlers ──────────────────────────────────────

// Timer interrupt (IRQ 0, remapped to interrupt 32).
// The PIT (Programmable Interval Timer) chip fires this ~18.2 times/sec.
//
// This is now the heartbeat of our scheduler. On each tick:
//   1. Send EOI to PIC (must be done BEFORE context switch, because
//      the switch might not return to this handler for a while)
//   2. Call the scheduler, which may context switch to another process
//
// CRITICAL: EOI must be sent BEFORE schedule(). If we switch to another
// process before sending EOI, the PIC thinks we're still handling this
// interrupt and blocks all future timer interrupts. The scheduler would
// never fire again.
extern "x86-interrupt" fn timer_interrupt_handler(_stack_frame: InterruptStackFrame) {
    // Send EOI first — before the scheduler potentially switches us out
    unsafe {
        PICS.lock()
            .notify_end_of_interrupt(InterruptIndex::Timer.as_u8());
    }

    // Call the scheduler — may context switch to another process.
    // If no processes are spawned, this is a no-op.
    crate::process::scheduler::schedule();
}

// Keyboard interrupt (IRQ 1, remapped to interrupt 33).
// Fires when a key is pressed OR released. The scancode is available
// at I/O port 0x60. We MUST read port 0x60 — if we don't, the keyboard
// controller won't send the next interrupt.
//
// We use the `pc-keyboard` crate to translate scancodes to characters.
// Scancodes are hardware-level codes (e.g., 0x1E = 'A' key pressed,
// 0x9E = 'A' key released). The crate handles shift, caps lock, etc.
extern "x86-interrupt" fn keyboard_interrupt_handler(_stack_frame: InterruptStackFrame) {
    use pc_keyboard::{layouts, DecodedKey, HandleControl, Keyboard, ScancodeSet1};
    use x86_64::instructions::port::Port;

    lazy_static! {
        static ref KEYBOARD: spin::Mutex<Keyboard<layouts::Us104Key, ScancodeSet1>> =
            spin::Mutex::new(Keyboard::new(
                ScancodeSet1::new(),
                layouts::Us104Key,
                HandleControl::Ignore,
            ));
    }

    let mut keyboard = KEYBOARD.lock();

    // Read the scancode from port 0x60 — this is the keyboard controller's
    // data port. Reading it also acknowledges the key event.
    let mut port = Port::new(0x60);
    let scancode: u8 = unsafe { port.read() };

    // add_byte: feed the raw scancode to the keyboard state machine.
    // Returns Ok(Some(event)) if a complete key event was recognized.
    if let Ok(Some(key_event)) = keyboard.add_byte(scancode) {
        // process_keyevent: converts the key event to a character,
        // handling shift, caps lock, etc.
        if let Some(key) = keyboard.process_keyevent(key_event) {
            match key {
                DecodedKey::Unicode(character) => print!("{}", character),
                DecodedKey::RawKey(key) => print!("{:?}", key),
            }
        }
    }

    unsafe {
        PICS.lock()
            .notify_end_of_interrupt(InterruptIndex::Keyboard.as_u8());
    }
}
